name: Back Build

on:
  push:
    paths:
      - 'src/back/**'

jobs:
  build-and-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Virtual Environment
      run: |
        cd src/back
        if ! command -v python3 &> /dev/null; then
          curl -O https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz
          tar -xzvf Python-3.9.0.tgz
          cd Python-3.9.0
          ./configure && make && sudo make install
          echo "export PYTHON3_PATH=/usr/local/bin/python3" > env.sh
        else
          echo "export PYTHON3_PATH=$(which python3)" > env.sh
        fi
        source env.sh
        $PYTHON3_PATH -m venv venv
        source venv/bin/activate && pip install -r requirements.txt

    - name: Install pytest and run tests
      run: |
        source src/back/env.sh
        source src/back/venv/bin/activate
        cd src/back
        find . -maxdepth 2 -type f -name "test_*.py" -exec sh -c '$PYTHON3_PATH -m unittest $(echo "{}" | sed "s/^.\///")' \;

        
    - name: Install build module and build Python package
      run: |
        source src/back/env.sh
        source src/back/venv/bin/activate
        cd src/back
        $PYTHON3_PATH -m pip install build
        $PYTHON3_PATH -m build --sdist

